apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: ticketing-microservice
build:
  local:
    push: false
  artifacts:
    - image: donyramadhan/ticketing_auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: "."
manifests:
  rawYaml:
    - infra/k8s/*.yaml
